apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: #CLUSTER_NAME#
  region: #CLUSTER_REGION#
  version: #CLUSTER_VERSION#

nodeGroups:
  - name: nodes
    instanceType: t3.large
    desiredCapacity: 3
    minSize: 3
    maxSize: 10
    kubeletExtraConfig:
      featureGates:
        EphemeralContainers: true
    # ssh:
    #   allow: true
    #   publicKeyName: kube-dev
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
